config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users, path: '',
  path_names: {sign_in: 'login', sign_up: 'registration', sign_out: 'logout'},
  controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users

  resources :rooms, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end

  get '/your_trips', to:'reservations#your_trips'
  get '/your_reservations', to: 'reservations#your_reservations'

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]
  get '/search', to: 'pages#search'
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!

  def create

    room = Room.find(params[:room_id])
    if current_user == room.user
      flash[:alert] = "You cannot book your own property!"
    else
      start_date = Date.parse(reservation_params[:start_date])
      end_date = Date.parse(reservation_params[:end_date])
      days = (end_date - start_date).to_i ; 1

      @reservation = current_user.reservations.build(reservation_params)
      @reservation.room = room
      @reservation.price = room.price
      @reservation.total = room.price * days
      @reservation.save

      flash[:notice] = "Booked Successfuly..."
    end
    redirect_to room
  end

  def your_trips
    @trips = current_user.reservations.order(start_date: :asc)
  end

  def your_reservations
    @rooms = current_user.rooms
  end

  private
    def reservation_params
      params.require(:reservation).permit(:start_date, :end_date)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<div class="card">
    <div class="card-header">
        <span>$ <%= @room.price %></span>
        <span class="float-left resservations-from-title pl-2">Per Night</span>
    </div>
    <div class="card-body">
        <%= form_for [@room, @reservation] do |f| %>
            <div class="row">
                <div class="col-6">
                    <label> Check In</label>
                    <%= f.text_field :start_date, placeholder: "Start date", class:"form-control" %>
                </div>

                <div class="col-6">
                    <label> Check Out</label>
                    <%= f.text_field :end_date, placeholder: "End date", class:"form-control", disabled: true %>
                </div>
            </div>

            <div class="message-header mt-2 text-center">
              <span id="message" class="massage"></span>
            </div>
            <div id="preview" style="display:none">
                <table class="reservation-table">
                    <tbody>
                        <tr>
                            <td>Price</td>
                            <td class="text-right">$<%= @room.price%></td>
                        </tr>

                        <tr>
                            <td>Night(s)</td>
                            <td class="text-right">×<span id="reservation-nights"></span></td>
                        </tr>

                        <tr>
                            <td class="total">Total</td>
                            <td class="text-right">$<span id="reservation-total"></span></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <%= f.submit "Book Now", class: "btn btn-info btn-block mt-4", id: "btn-book", disabled: true %>
        <% end %>
    </span>
</div>

<script>

function checkDate(date) {
  dmy = date.getDate() + "-" + (date.getMonth() + 1) + "-" + date.getFullYear();
  return [$.inArray(dmy, unavailableDates) == -1];
};

  $(function(){

    unavailableDates = [];

    $.ajax({
      url: '<%= preload_room_path(@room) %>',
      dataTyp: 'json',
      success: function(data){
        $.each(data, function(arrID, arrValue){
          for (var d = new Date(arrValue.start_date); d <= new Date(arrValue.end_date); d.setDate(d.getDate() + 1)){
            unavailableDates.push($.datepicker.formatDate('d-m-yy',d));
          }
        });

      $('#reservation_start_date').datepicker({
        dateFormat: 'dd-mm-yy',
        minDate: 0,
        maxDate: '3m',
        beforeShowDay: checkDate,
        onSelect: function(selected) {
          $('#reservation_end_date').datepicker("option", "minDate", selected);
          $('#reservation_end_date').attr("disabled", false);
        }
      });

      $('#reservation_end_date').datepicker({
        dateFormat: 'dd-mm-yy',
        minDate: 0,
        maxDate: '3m',
        beforeShowDay: checkDate,
        onSelect: function(selected) {
          $('#reservation_start_date').datepicker("option", "maxDate", selected);
          var start_date = $('#reservation_start_date').datepicker('getDate');
          var end_date = $('#reservation_end_date').datepicker('getDate');
          var nights = (end_date - start_date)/1000/60/60/24 + 1;
          var input = {
            'start_date' : start_date,
            'end_date' :end_date
          }

          $.ajax({
            url: '<%= preview_room_path(@room) %>',
            data: input,
            success: function(data) {
              if (data.conflict) {
                $('#message').text("These dates are not available");
                $('#preview').hide();
                $('#btn-book').attr('disabled', true);
              } else{
                $('#message').text("");
                $('#preview').show();
                $('#btn-book').attr('disabled', false);
                var total = nights * <%= @room.price %>;
                $('#reservation-nights').text(nights);
                $('#reservation-total').text(total);
              }
            }
          });
        }
      });
      }
    });
  });
</script>

app/views/reservations/your_reservations.html.erb
<div class="row">
    <div class="col-3">
        <div class="card">
            <div class="card-body">
                <%= render "rooms/room_listing_menu" %>
            </div>
        </div>
    </div>


    <div class="col-9">
        <div class="card">
            <div class="card-header bg-warning text-center">
                Your Reservations
            </div>
            <div class="card-body">
                <div class="container">
                    <% @rooms.each do |room| %>
                        <% room.reservations.each do |reservation| %>
                            <div class="row room-row mb-3">
                                <div class="col-md-2 pr-0 trip-date">
                                    <%= reservation.start_date.strftime('%v') %>
                                </div>
                                <div class="col-md-2">
                                    <% if reservation.room.photos.blank? %>
                                        <%= image_tag "no-image.png", alt: "Room image", class: "room-image mt-1" %>
                                    <% else %>
                                        <%= image_tag reservation.room.photos.first.image.url(:thumb), class:"mt-1" %>
                                    <% end %>
                                </div>
                                <div class="col-md-5">
                                    <div class="ml-4">
                                        <%= link_to reservation.room.listing_name, room_path(reservation.room), class: "trip-name reservations-a-tag" %><br><br>
                                    </div>
                                    <span>
                                        <%= image_tag avatar_url(reservation.user), class: "rounded-circle avatar-small mr-2" %>
                                        <%= link_to reservation.user.fullname, user_path(reservation.user), class: "reservations-a-tag" %>
                                    </span>
                                </div>
                                <div class="col-md-3 mt-3">
                                    <%= render partial: "reviews/host_form", locals: {reservation: reservation} %>
                                </div>
                            </div>
                            <hr>
                        <% end %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/reservations/your_trips.html.erb
<div class="row">
    <div class="col-3">
        <div class="card">
            <div class="card-body pb-1">
                <%= render "rooms/room_listing_menu" %>
            </div>
        </div>
    </div>

    <div class="col-9">
        <div class="card">
            <div class="card-header bg-danger  text-white text-center">
                Your Trips
            </div>
            <div class="card-body">
                <div class="container">
                    <% @trips.each do |trip| %>
                        <div class="row">
                            <div class="col-md-2 pr-0">
                                <%= trip.start_date.strftime('%v')%>
                            </div>
                            <div class="col-md-2 mt-2">
                                <div class="media mb-2 media-container">
                                    <% if trip.room.photos.blank? %>
                                        <%= image_tag 'no-image-icon.png', class: "img-size" %>
                                    <% else %>
                                        <%= image_tag trip.room.photos.first.image.url(:thumb) %>
                                    <% end %>
                                </div>
                            </div>
                            <div class="col-md-5">
                                <div class="ml-4">
                                    <%= link_to trip.room.listing_name, room_path(trip.room), class: "reservations-a-tag" %><br><br>
                                </div>
                                <span>
                                    <%= image_tag avatar_url(trip.room.user), class: "rounded-circle avatar-small mr-2" %>
                                    <%= link_to trip.room.user.fullname, user_path(trip.room.user), class: "reservations-a-tag" %>
                                </span>
                            </div>
                            <div class="col-md-3 mt-3">
                                <%= render partial: "reviews/guest_form", locals: {reservation: trip} %>
                            </div>
                        </div>
                        <hr>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>