config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users, path: '',
  path_names: {sign_in: 'login', sign_up: 'registration', sign_out: 'logout'},
  controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users

  resources :rooms, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end

  get '/your_trips', to:'reservations#your_trips'
  get '/your_reservations', to: 'reservations#your_reservations'

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]
  get '/search', to: 'pages#search'
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :photos
  has_many :reservations
  has_many :guest_reviews


  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :home_type, presence: true
  validates :room_type, presence: true
  validates :accommodate, presence: true
  validates :bedroom, presence: true
  validates :bathroom, presence: true
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :set_room, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show]

  def index
    @rooms = current_user.rooms
  end

  def new
    @room = current_user.rooms.build
  end

# notice:はredirect＿to のみ使う
# renderはflashを使う
  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      redirect_to listing_room_path(@room), notice: "Saved..."
    else
      flash[:alert] = "Something went wrong..."
      render :new
    end
  end

  def show
    @photos = @room.photos
    @reservation = Reservation.new
    @guest_reviews = @room.guest_reviews
  end

  def listing
  end

  def pricing
  end

  def description
  end

  def photo_upload
    @photos = @room.photos
  end

  def amenities
  end

  def location
  end

  def update
    if @room.update(room_params)
      flash[:notice] = "Saved..."
    else
      flash[:alert] = "Something went wrong..."
    end
      # 同じ場所に移動する
      redirect_back(fallback_location: request.referer)
  end

  #Reservation
  def preload
    reservations = @room.reservations
    render json: reservations
  end

  def  preview
    start_date = Date.parse(params[:start_date])
    end_date = Date.parse(params[:end_date])

    output = {
      conflict: is_conflict(start_date, end_date, @room)
    }

    render json: output
  end

  private

    def is_conflict(start_date, end_date, room)
      check = room.reservations.where("? < start_date AND end_date < ?", start_date, end_date)
      check.size > 0 ? true : false
      # if check.size > 0
      #   true
      #   else
      #   false
      # end
    end

    def set_room
      @room = Room.find(params[:id])
    end

    def room_params
      params.require(:room).permit(:home_type, :room_type, :accommodate, :bedroom, :bathroom, :listing_name, :summary, :address, :is_tv, :is_kitchen, :is_air, :is_heating, :is_internet, :price, :active )
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_room_list.html.erb
<% @rooms.each do |room| %>
    <div class="col-4">
        <div class="card">
            <div class="card-header preview">
                <%= image_tag room.photos.first.image.url(:medium) %>
            </div>
            <div class="card-body room-body">
                <%= link_to room.listing_name, room %><br><br>
                $<%= room.price %> - <%= room.home_type %>
            </div>
        </div>
    </div>
<% end %>

app/views/rooms/_room_listing_menu.html.erb
<div class="room-menu">
    <ul>
        <li><%= link_to 'Your Listings', rooms_path %></li>
        <li class="mt-3"><%= link_to 'Your Reservations', your_reservations_path %></li>
        <li class="mt-3"><%= link_to 'Your Trips', your_trips_path %></li>
    </ul>
</div>

app/views/rooms/_room_menu.html.erb
<div class="room-menu">
    <ul>
        <li>
            <%= link_to 'Listing', listing_room_path %>
            <span class="float-right"><i class="fa fa-check"></i></span>
        </li>
        <li class="mt-2">
            <%= link_to 'Pricing', pricing_room_path %>
            <% if !@room.price.blank? %>
                <span class="float-right"><i class="fa fa-check"></i></span>
            <% end %>
        </li>
        <li class="mt-2">
            <%= link_to 'Description', description_room_path %>
            <% if !@room.listing_name.blank? %>
                <span class="float-right"><i class="fa fa-check"></i></span>
            <% end %>
        </li>
        <li class="mt-2">
            <%= link_to 'Photos', photo_upload_room_path %>
            <% if !@room.photos.blank? %>
                <span class="float-right"><i class="fa fa-check"></i></span>
            <% end %>
        </li>
        <li class="mt-2">
            <%= link_to 'Amenities', amenities_room_path %>
            <span class="float-right"><i class="fa fa-check"></i></span>
        </li>
        <li class="border-bottom border-secondary mt-2  pb-2">
            <%= link_to 'Location', location_room_path %>
            <% if !@room.address.blank? %>
            <span class="float-right"><i class="fa fa-check"></i></span>
            <% end %>
        </li>
    </ul>
</div>

<% is_ready = ! @room.price.blank? && !@room.listing_name.blank? && !@room.photos.blank? && !@room.address.blank? %>

<%# <%= link_to 'Publish', root_path, class: "btn btn-outline-danger btn-block" %>

<%= form_for @room do |f|%>
    <%= f.hidden_field :active, value:true %>
    <%= f.submit "Publish", class: "btn btn-outline-danger btn-block", disabled: !is_ready %>
<% end %>

app/views/rooms/amenities.html.erb
<div class="row">
    <div class="col-3">
        <div class="card">
            <div class="card-body">
                <%= render "room_menu" %>
            </div>
        </div>
    </div>

    <div class="col-9">
        <div class="card">
            <div class="card-header text-white bg-success pl-3">
                Amenities
            </div>
            <div class="card-body">
                <div class="container">
                    <%= form_for @room do |f| %>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label> TV </label>
                                    <%= f.check_box :is_tv, id: :checkbox,:as => :boolean %>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label> Kitchen </label>
                                    <%= f.check_box :is_kitchen, id: :checkbox,:as => :boolean %>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label> Internet </label>
                                    <%= f.check_box :is_internet, id: :checkbox,:as => :boolean %>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group mt-2">
                                    <label> Heating </label>
                                    <%= f.check_box :is_heating, id: :checkbox,:as => :boolean %>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group mt-2">
                                    <label> Air Conditioning </label>
                                    <%= f.check_box :is_air, id: :checkbox,:as => :boolean %>
                                </div>
                            </div>
                        </div>
                        <div class="text-center mt-1">
                            <%= f.submit "Save", class: "btn btn-primary room-form-btn"%>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/rooms/description.html.erb
<div class="row">
    <div class="col-3">
        <div class="card">
            <div class="card-body">
                <%= render "room_menu" %>
            </div>
        </div>
    </div>

    <div class="col-9">
        <div class="card">
            <div class="card-header text-white bg-success pl-3">
                Description
            </div>
            <div class="card-body">
                <div class="container">
                    <%= form_for @room do |f| %>
                        <div class="form-group">
                            <label>Listing Name</label>
                            <%= f.text_field :listing_name, placeholder: "What is your listing name?", class: "form-control", required: true %>
                        </div>
                        <div class="form-group">
                            <label>Summary</label>
                            <%= f.text_area :summary, placeholder: "Summary of your house", class: "form-control", rows: 5, required: true %>
                        </div>
                        <div class="text-center">
                            <%= f.submit "Save", class: "btn btn-primary mt-2 mb-1 room-form-btn" %>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/rooms/index.html.erb
<div class="row">
    <div class="col-3">
        <div class="card">
            <div class="card-body pb-1">
                <%= render "room_listing_menu" %>
            </div>
        </div>
    </div>

    <div class="col-9">
        <div class="card">
            <div class="card-header text-white bg-info text-center">
                Your Listings
            </div>
            <div class="card-body">
                <div class="container">
                    <% @rooms.each do |room| %>
                        <div class="row">
                            <div class="col-md-2 mt-2">
                                <div class="media mb-4 media-container">
                                    <% if room.photos.blank? %>
                                        <%= image_tag 'no-image-icon.png', class: "img-size" %>
                                    <% else %>
                                        <%= image_tag room.photos.first.image.url(:thumb) %>
                                    <% end %>
                                </div>
                            </div>
                            <div class="col-md-7 mt-4 text-center">
                                <%= room.listing_name %>
                            </div>
                            <div class="col-md-3 mt-3">
                                <%= link_to 'Update', listing_room_path(room), class: "btn btn-primary btn-block btn-lg active room-form-btn" %>
                            </div>
                        </div>
                        <hr class="mt-0 mb-2">
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/rooms/listing.html.erb
<div class="row">
    <div class="col-3">
        <div class="card">
            <div class="card-body">
                <%= render "room_menu" %>
            </div>
        </div>
    </div>

    <div class="col-9">
        <div class="card">
            <div class="card-header text-white bg-success pl-3">
                Listing
            </div>
            <div class="card-body">
                <div class="container">
                    <%= form_for @room do |f| %>
                        <div class="row">
                            <div class="col-4">
                                <div class="form-group mt-2">
                                    <label>Home Type</label><br>
                                    <div class="list-form-control">
                                        <%# 2回Apartmentとかを繰り返すのはdbに保存と画面上に出すため %>
                                        <%= f.select :home_type, [["Apartment", "Apartment",], ["House", "House"], ["Bed & Breakfast", "Bed & Breakfast"]], id:"home_type", prompt:"Select...", class: "form-control" %>
                                    </div>
                                </div>
                            </div>

                            <div class="col-4">
                                <div class="form-group mt-2">
                                    <label>Room Type</label><br>
                                    <div class="list-form-control">
                                        <%= f.select :room_type, [["Entire", "Entire"], ["Private", "Private"], ["Shared", "Shared"]], id:"room_type", prompt:"Select...", class: "form-control" %>
                                    </div>
                                </div>
                            </div>

                            <div class="col-4">
                                <div class="form-group mt-2">
                                    <label>Accommodate</label><br>
                                    <div class="list-form-control">
                                        <%= f.select :accommodate, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],id:"accommodate", prompt:"Select...", class: "form-control" %>
                                    </div>
                                </div>
                            </div>

                            <div class="col-4">
                                <div class="form-group mt-2">
                                    <label>Bedrooms</label><br>
                                    <div class="list-form-control">
                                        <%= f.select :bedroom, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]], id:"bedroom", prompt:"Select...", class: "form-control" %>
                                    </div>
                                </div>
                            </div>

                            <div class="col-4">
                                <div class="form-group mt-2">
                                    <label>Bathrooms</label><br>
                                    <div class="list-form-control">
                                        <%= f.select :bathroom, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]], id:"bathroom", prompt:"Select...", class: "form-control" %>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="mt-2">
                            <%= f.submit "Create My Room", class: "btn btn-danger" %>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/rooms/location.html.erb
<div class="row">
    <div class="col-3">
        <div class="card">
            <div class="card-body">
                <%= render "room_menu" %>
            </div>
        </div>
    </div>

    <div class="col-9">
        <div class="card">
            <div class="card-header text-white bg-success pl-3">
                Location
            </div>
            <div class="card-body">
                <div class="container">
                    <%= form_for @room do |f| %>
                        <div class="form-group">
                            <label>Address</label>
                            <%= f.text_field :address, placeholder: "What is your address?", class: "form-control", required: true %>

                            <div class="text-center mt-1">
                                <%= f.submit "Save", class: "btn btn-primary mt-3 room-form-btn" %>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/rooms/new.html.erb
<div class="card">
    <div class="card-header text-white bg-success">
        Create your beautiful places
    </div>
    <div class="card-body">
        <div class="container">
            <%= form_for @room do |f| %>
                <div class="row">
                    <div class="col-4">
                        <div class="form-group">
                            <label>Home Type</label><br>
                            <div class="list-form-control">
                                <%# 2回Apartmentとかを繰り返すのはdbに保存と画面上に出すため %>
                                <%= f.select :home_type, [["Apartment", "Apartment",], ["House", "House"], ["Bed & Breakfast", "Bed & Breakfast"]], id:"home_type", prompt:"Select...", class: "form-control" %>
                            </div>
                        </div>
                    </div>

                    <div class="col-4">
                        <div class="form-group">
                            <label>Room Type</label><br>
                            <div class="list-form-control">
                                <%= f.select :room_type, [["Entire", "Entire"], ["Private", "Praivate"], ["Shared", "Shared"]], id:"room_type", prompt:"Select...", class: "form-control" %>
                            </div>
                        </div>
                    </div>

                    <div class="col-4">
                        <div class="form-group">
                            <label>Accommodate</label><br>
                            <div class="list-form-control">
                                <%= f.select :accommodate, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],id:"accommodate", prompt:"Select...", class: "form-control" %>
                            </div>
                        </div>
                    </div>

                    <div class="col-4">
                        <div class="form-group">
                            <label>Bedrooms</label><br>
                            <div class="list-form-control">
                                <%= f.select :bedroom, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]], id:"bedroom", prompt:"Select...", class: "form-control" %>
                            </div>
                        </div>
                    </div>

                    <div class="col-4">
                        <div class="form-group">
                            <label>Bathrooms</label><br>
                            <div class="list-form-control">
                                <%= f.select :bathroom, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]], id:"bathroom", prompt:"Select...", class: "form-control" %>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="mt-2">
                    <%= f.submit "Create My Room", class: "btn btn-danger" %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/rooms/photo_upload.html.erb
<div class="row">
    <div class="col-3">
        <div class="card">
            <div class="card-body">
                <%= render "room_menu" %>
            </div>
        </div>
    </div>

    <div class="col-9">
        <div class="card">
            <div class="card-header text-white bg-success pl-3">
                Photos
            </div>
            <div class="card-body">
                <div class="container">
                    <div class="row">
                        <div class="offset-3 col-6">
                            <%= form_for @room, url: room_photos_path(@room), method: 'post', html: {multipart:true} do |f| %>
                                <div class="form-group mt-3">
                                    <span>
                                        <%= file_field_tag "images[]", type: :file, multiple: true, class: "btn btn-outline-secondary"%>
                                    </span>
                                </div>

                                <div class="text-center mt-4">
                                    <%= f.submit "Add Photos", class: "btn btn-danger" %>
                                </div>
                            <% end %>
                        </div>
                        <%= render "photos/photos_list" %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/rooms/pricing.html.erb
<div class="row">
    <div class="col-3">
        <div class="card">
            <div class="card-body">
                <%= render "room_menu" %>
            </div>
        </div>
    </div>

    <div class="col-9">
        <div class="card">
            <div class="card-header text-white bg-success pl-3">
                Price
            </div>
            <div class="card-body">
                <div class="container">
                    <%= form_for @room do |f| %>
                        <div class="form-group">
                            <label>Price</label>
                            <%= f.text_field :price, placeholder: "eg: 100", class: "form-control", required: true %>

                            <div class="text-center mt-1">
                                <%= f.submit "Save", class: "btn btn-primary mt-3 room-form-btn" %>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/rooms/show.html.erb
<div id="wrapper">
    <div class="row">
        <div class="col-12 mb-1">
            <%= image_tag @room.photos.first.image.url, width:"100%" %>
        </div>
    </div>
    <div class="row mt-4">
        <div class=col-8>
            <div class="row">
                <div class="col-8">
                    <h3 class="mb-4"><%= @room.listing_name %></h3>
                    <p><%= @room.address%></p>
                </div>
                <div class="col-4 text-center">
                    <div class="mb-3">
                        <%= image_tag avatar_url(@room.user), class:"rounded-circle" %><br>
                    </div>
                    <%= @room.user.fullname%>
                </div>
            </div>
            <hr>

            <div class="row">
                <div class="col-3 text-center">
                    <i class="fa fa-home"></i>
                    <%= @room.home_type %>
                </div>
                <%# pluralizeはintegerのみに使う。だからstringには使わない %>
                <div class="col-3 text-center">
                    <i class="fa fa-user-circle"></i>
                    <%= pluralize(@room.accommodate, "Guest") %>
                </div>
                <div class="col-3 text-center">
                    <i class="fa fa-bed"></i>
                    <%= pluralize(@room.bedroom, "Bedroom") %>
                </div>
                <div class="col-3 text-center">
                    <i class="fa fa-bath"></i>
                    <%= pluralize(@room.bathroom, "Bathroom") %>
                </div>
            </div>
            <hr>

            <div class="row">
                <div class="col-12">
                    <h3 class="mb-4">About This Listing</h3>
                    <%= @room.summary %>
                </div>
            </div>
            <hr>

            <div class="row">
                <div class="col-4">
                    <h3>Amenities</h3>
                </div>
                <div class="col-4 mt-5">
                    <ul>
                        <li class=" <%= 'text-line-through' if !@room.is_tv %>">TV</li>
                    </ul>
                    <ul>
                        <li class=" <%= 'text-line-through' if !@room.is_kitchen %>">KITCHEN</li>
                    </ul>
                    <ul>
                        <li class=" <%= 'text-line-through' if !@room.is_internet %>">INTERNET</li>
                    </ul>
                </div>
                <div class="col-4 mt-5">
                    <ul>
                        <li class=" <%= 'text-line-through' if !@room.is_heating %>">HEATING</li>
                    </ul>
                    <ul>
                        <li class=" <%= 'text-line-through' if !@room.is_air %>">AIR CONDITIONING</li>
                    </ul>
                </div>
            </div>
            <hr>

            <%# Carousel %>
            <div class="row mb-3">
                <div class="col-md-12">
                    <% if @photos.length > 0 %>
                        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <% @photos.each do |photo| %>
                                    <li data-target="#carouselExampleIndicators" data-slide-to="<%= photo.id %>"></li>
                                <% end %>
                            </ol>
                            <div class="carousel-inner">
                                <% @photos.each do |photo| %>
                                    <div class="carousel-item <%= 'active' if photo.id == @photos[0].id %>">
                                        <%= image_tag photo.image.url(), class: "d-block w-100" %>
                                    </div>
                                <% end %>
                            </div>
                            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    <% end %>
                </div>
            </div>
            <hr>


            <%# reviews %>

            <div class="row">
                <div class="col-12">
                    <h3><%= pluralize(@guest_reviews.count, "Review") %></h3>
                    <div  class="container">
                        <div>
                            <%= render "reviews/guest_list" %>
                        </div>
                    </div>
                </div>
            </div>
            <hr>

            <%# google map %>

            <div class="row mb-3">
                <h3 class="mb-3">Google Map</h3>
                <div id="map" style="width:100%; height:400px;">
                    <script src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.credentials.google_maps_api_key%>"></script>
                    <script>
                        function initialize(){
                            var location = {lat: <%= @room.latitude %>, lng: <%= @room.longitude %>};
                            var map = new google.maps.Map(document.getElementById('map'),{
                            center: location,
                            zoom: 14
                        });

                        var marker = new google.maps.Marker({
                            position: location,
                            map: map
                        });

                        var infoWindow = new google.maps.InfoWindow({
                            content: '<div id="content"><%= image_tag @room.photos.first.image.url(:medium) %></div>'
                        });

                        infoWindow.open(map, marker)

                        }

                        google.maps.event.addDomListener(window, 'load', initialize);
                    </script>
                </div>
            </div>
            <hr>

            <%# //near by places %>

            <div>
                <h3 class="mb-3">Near By </h3>
                <div class="row mb-3">
                    <% for room in @room.nearbys(10) %>
                        <div class="col-4">
                            <div class="card mb-3">
                                <div class="card-header preview">
                                    <%= image_tag room.photos.first.image.url(:medium) %>
                                </div>
                                <div class="card-body near-by-list-name">
                                    <%= link_to room.listing_name, room %>
                                    <%# round(2)は小数点２つまでということ %>
                                    (<%= room.distance.round(2) %> miles away)
                                </div>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>

        </div>
        <div class="col-4">
            <%= render 'reservations/form' %>
        </div>
    </div>
</div>