config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users, path: '',
  path_names: {sign_in: 'login', sign_up: 'registration', sign_out: 'logout'},
  controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users

  resources :rooms, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end

  get '/your_trips', to:'reservations#your_trips'
  get '/your_reservations', to: 'reservations#your_reservations'

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]
  get '/search', to: 'pages#search'
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :room
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def create
    @room = Room.find(params[:room_id])
    if params[:images]
        params[:images].each do |img|
          @room.photos.create(image: img)
        end
        redirect_back(fallback_location: request.referer, notice: "Saved")
    end
  end

  def destroy
    @photo =  Photo.find(params[:id])
    @photo.destroy
    redirect_back(fallback_location: request.referer, notice: "Photo Delete")
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_photos_list.html.erb
<% if @photos.count > 0 %>
    <br><br>

    <div class="row">
        <% @photos.each do |photo| %>
            <div class="col-4">
                <div class="card mt-4">
                    <div class="card-header preview p-0">
                        <%= image_tag photo.image.url %>
                    </div>

                    <div class="card-body">
                        <span class="float-right photo-list-card-body-li">
                            <%= link_to room_photo_path(photo.room_id, photo), method: :delete, data: {confirm: "Are you sure?"} do %>
                                <i class="fa fa-trash fa-lg faa-float animated"></i>
                            <% end %>
                        </span>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
<% end %>