config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users, path: '',
  path_names: {sign_in: 'login', sign_up: 'registration', sign_out: 'logout'},
  controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users

  resources :rooms, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end

  get '/your_trips', to:'reservations#your_trips'
  get '/your_reservations', to: 'reservations#your_reservations'

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]
  get '/search', to: 'pages#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guest_review.rb
class GuestReview < Review
    belongs_to :guest, class_name: "User"
end

app/models/host_review.rb
class HostReview < Review
  belongs_to :host, class_name: "User"
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :room
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :photos
  has_many :reservations
  has_many :guest_reviews


  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :home_type, presence: true
  validates :room_type, presence: true
  validates :accommodate, presence: true
  validates :bedroom, presence: true
  validates :bathroom, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable,
        :confirmable, :omniauthable

  validates :fullname, presence: true, length: { maximum: 50}
  has_many :rooms, dependent: :destroy
  has_many :reservations

  has_many :guest_reviews, class_name: "GuestReview", foreign_key: "guest_id"
  has_many :host_reviews, class_name: "HostReview", foreign_key: "host_id"



  def self.from_omniauth(auth)

    user = User.where(email: auth.info.email).first

    if user
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0, 20]
        user.fullname = auth.info.name   # assuming the user model has a name
        user.image = auth.info.image # assuming the user model has an image
        user.uid = auth.uid
        user.provider = auth.provider
        # If you are using confirmable and the provider(s) you use validate emails,
        # uncomment the line below to skip the confirmation emails.
        user.skip_confirmation!
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname])
      devise_parameter_sanitizer.permit(:account_update, keys: [:fullname, :phone_number, :description])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @rooms = Room.where(active: true).limit(3)
  end

  def search
    #Step 1 - assign session here
    if params[:search].present?
      #Create session
      session[:loc_search] = params[:search]
    end

    #Step 2
    if session[:loc_search]
      #Grab all cities and nearby cities
      @rooms_address = Room.where(active: true).near(session[:loc_search], 5, order: 'distance')
    else
      #Grab all places here
      @rooms_address = Room.where(active: true).all
    end

    #Step 3 - For ransack usage
    @search = @rooms_address.ransack(params[:q])
    @rooms = @search.result
    @arrRooms = @rooms.to_a

    #Step 4
    #Check if start date and end date is empty
    if (params[:start_date] && params[:end_date] && !params[:start_date].empty? && !params[:end_date].empty?)
      @start_date = Date.parse(params[:start_date])
      @end_date = Date.parse(params[:end_date])
      @rooms.each do |room|
        taken_room = room.reservations.where("? <= start_date AND start_date <=? OR (? <= end_date AND end_date <= ? )",
        @start_date, @end_date,
        @start_date, @end_date).limit(1)

        #ここでdeleteしてroom2とかroom3にループする
        if taken_room.any?
          @arrRooms.delete(room)
        end
      end
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def create
    @room = Room.find(params[:room_id])
    if params[:images]
        params[:images].each do |img|
          @room.photos.create(image: img)
        end
        redirect_back(fallback_location: request.referer, notice: "Saved")
    end
  end

  def destroy
    @photo =  Photo.find(params[:id])
    @photo.destroy
    redirect_back(fallback_location: request.referer, notice: "Photo Delete")
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :set_room, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show]

  def index
    @rooms = current_user.rooms
  end

  def new
    @room = current_user.rooms.build
  end

# notice:はredirect＿to のみ使う
# renderはflashを使う
  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      redirect_to listing_room_path(@room), notice: "Saved..."
    else
      flash[:alert] = "Something went wrong..."
      render :new
    end
  end

  def show
    @photos = @room.photos
    @reservation = Reservation.new
    @guest_reviews = @room.guest_reviews
  end

  def listing
  end

  def pricing
  end

  def description
  end

  def photo_upload
    @photos = @room.photos
  end

  def amenities
  end

  def location
  end

  def update
    if @room.update(room_params)
      flash[:notice] = "Saved..."
    else
      flash[:alert] = "Something went wrong..."
    end
      # 同じ場所に移動する
      redirect_back(fallback_location: request.referer)
  end

  #Reservation
  def preload
    reservations = @room.reservations
    render json: reservations
  end

  def  preview
    start_date = Date.parse(params[:start_date])
    end_date = Date.parse(params[:end_date])

    output = {
      conflict: is_conflict(start_date, end_date, @room)
    }

    render json: output
  end

  private

    def is_conflict(start_date, end_date, room)
      check = room.reservations.where("? < start_date AND end_date < ?", start_date, end_date)
      check.size > 0 ? true : false
      # if check.size > 0
      #   true
      #   else
      #   false
      # end
    end

    def set_room
      @room = Room.find(params[:id])
    end

    def room_params
      params.require(:room).permit(:home_type, :room_type, :accommodate, :bedroom, :bathroom, :listing_name, :summary, :address, :is_tv, :is_kitchen, :is_air, :is_heating, :is_internet, :price, :active )
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @rooms = @user.rooms
    # Display all the guest reviews to host (if this user is a host)
    @guest_reviews = Review.where(type: "GuestReview", host_id: @user.id)
    # Display all the guest reviews to host (if this user is a guest)
    @host_reviews = Review.where(type: "HostReview", guest_id: @user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    if user .image
      "http://graph.facebook.com/#{user.uid}/picture?type=large"
    else
      gravatar_id = Digest::MD5::hexdigest(user.email).downcase
      "https://www.gravatar.com/avatar/#{gravatar_id}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container mb-1">
        <%= link_to image_tag("icon.png", style: "height:45px; width:auto;"), '/', class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <%= form_tag search_path, class: "form-inline", method: :get do %>
                <div class="form-group">
                    <%= text_field_tag :search, params[:search], placeholder: "Anywhere?", class: "form-control" %>
                </div>
            <% end %>
            <ul class="navbar-nav ml-auto">
                <%= link_to 'Become Host', new_room_path, class: "btn btn-outline-light text-right mr-2 pt-2"%>
                <% if signed_in?%>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"  aria-expanded="false">
                            <%= image_tag avatar_url(current_user), class: "rounded-circle avatar-small mr-2"%>
                            <%= current_user.fullname %>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <%= link_to "Manage Listing", rooms_path, class: "dropdown-item"%>
                            <%= link_to "List Your Spaces", new_room_path, class: "dropdown-item"%>
                            <%= link_to "Your Reservations", your_reservations_path, class: "dropdown-item"%>
                            <%= link_to "Your Trips", your_trips_path, class: "dropdown-item"%>
                        <div class="dropdown-divider" ></div>
                            <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item"%>
                            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                        </>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to "Sign-up", new_user_registration_path, class: "nav-link"%>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Login", new_user_session_path, class: "nav-link"%>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>ShinyaAirbnb</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
        <link rel="stylesheet" href="https://code.jquery.com/ui/1.11.4/themes/blitzer/jquery-ui.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome-animation/0.0.10/font-awesome-animation.css" type="text/css" media="all" />
        <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
    </head>

    <body>
        <%= render 'layouts/header'%>
        <% unless flash.empty? %>
            <script type="text/javascript">
                <% flash.each do |type, message| %>
                    <% type = 'success' if type === 'notice' %>
                    <% type = 'error' if type === 'alert' %>
                    toastr['<%= type %>'] ('<%= message %>')
                <% end %>
            </script>
        <% end %>
        <div class="container mt-4">
            <%= yield %>
        </div>
    </body>
</html>

app/views/pages/home.html.erb
<div class="row">
    <div class="col-md-7 banner">
        <h2><span class="text-danger">Airbnb </span>Book unique homes and experience a city like a local.</h2>
    </div>
</div>

<%= form_tag search_path, method: :get do %>
    <div class="row">
        <div class="col-md-6">
            <%= text_field_tag :search, params[:search], placeholder: "Where are you going?", class: "form-control" %>
        </div>
        <div class="col-md-3">
            <%= text_field_tag :start_date, params[:start_date], placeholder: "Start Date", class: "form-control" %>
        </div>
        <div class="col-md-3">
            <%= text_field_tag :end_date, params[:end_date], placeholder: "End Date", class: "form-control" %>
        </div>
    </div><br><br>

    <div class="row">
        <div class="col-md-4 mx-auto">
            <%= submit_tag "Search", class: "btn btn-primary btn-block" %>
        </div>
    </div>
<% end %>


<div class="row">
    <div><h3>Homes</h3></div>
    <div class="row text-center home-list">
        <%= render "rooms/room_list" %>
    </div>
</div>
<br>

<div class="mt-2"><h3>Cities</h3></div>
<br>
<div class="row">
    <div class="col-md-3">
        <a href="https://shinyaairbnb.herokuapp.com/search?utf8=%E2%9C%93&search=los+angeles&start_date=&end_date=&commit=Search">
            <div class="discovery-card" style="background-image: url('/assets/LA.jpg')"></div>
        </a>
    </div>

    <div class="col-md-3">
        <a href="https://shinyaairbnb.herokuapp.com/search?utf8=%E2%9C%93&search=london&start_date=&end_date=&commit=Search">
            <div class="discovery-card" style="background-image: url('/assets/LD.jpg')"></div>
        </a>
    </div>

    <div class="col-md-3">
        <a href="https://shinyaairbnb.herokuapp.com/search?utf8=%E2%9C%93&search=paris&start_date=&end_date=&commit=Search">
            <div class="discovery-card" style="background-image: url('/assets/paris.jpg')"></div>
        </a>
    </div>

    <div class="col-md-3">
        <a href="https://shinyaairbnb.herokuapp.com/search?utf8=%E2%9C%93&search=miami&start_date=&end_date=&commit=Search">
            <div class="discovery-card" style="background-image: url('/assets/miami.jpg')"></div>
        </a>
    </div>
</div><br><br>

<script>
  $('#start_date').datepicker({
      dateFormat: 'dd-mm-yy',
      minDate: 0,
      maxDate: '3m',
      onSelect: function(selected) {
      $('#end_date').datepicker("option", "minDate", selected);
    }
    });

    $('#end_date').datepicker({
      dateFormat: 'dd-mm-yy',
      minDate: 0,
      maxDate: '3m',
      onSelect: function(selected) {
      $('#start_date').datepicker("option", "maxDate", selected);
    }
  });
</script>

app/views/pages/search.html.erb
<div id="main">
    <div id="left">
        <div class="row">
            <div class="col-md-4 mx-auto">
                <button id="filter" class="btn btn-primary" data-toggle="collapse" data-target="#collapsePanel">
                More Filters<i class="fa fa-chevron-down"></i>
                </button>
            </div>
        </div>

        <div>
            <br>
            <div class="collapse" id="collapsePanel">
                <%= search_form_for @search, url: search_path do |f| %>
                    <div class="row">
                        <div class="col-md-8">
                            <label>Price Range: </label>
                            <div id="slider-range"></div>
                        </div>
                        <div class="col-md-2">
                            <label>Min Price: </label>
                            <%= f.text_field :price_gteq, class: "form-control" %>
                        </div>
                        <div class="col-md-2">
                            <label>Max Price: </label>
                            <%= f.text_field :price_lteq, class: "form-control" %>
                        </div>
                    </div>
                    <hr>

                    <div class="row">
                        <div class="col-md-6">
                            <%= text_field_tag :start_date, params[:start_date], placeholder: "Start Date", class: "form-control" %>
                        </div>
                        <div class="col-md-6">
                            <%= text_field_tag :end_date, params[:end_date], placeholder: "End Date", class: "form-control" %>
                        </div>
                    </div>
                    <hr>

                    <div class="row">
                        <div class="col-md-4">
                            <%= check_box_tag "q[room_type_eq_any][]", "Entire" %> Entire Rooms
                        </div>
                        <div class="col-md-4">
                            <%= check_box_tag "q[room_type_eq_any][]", "Private" %> Private Rooms
                        </div>
                        <div class="col-md-4">
                            <%= check_box_tag "q[room_type_eq_any][]", "Share" %> Shared Rooms
                        </div>
                    </div>
                    <hr>

                    <div class="row">
                        <div class="col-md-4">
                            <label>Accommodate</label><br>
                            <div class="list-form-control">
                                <%= f.select :accommodate_gteq, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],id:"accommodate", prompt:"Select...", class: "form-control" %>
                            </div>
                        </div>

                        <div class="col-md-4">
                            <label>Bedrooms</label><br>
                            <div class="list-form-control">
                                <%= f.select :bedroom_gteq, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]], id:"bedroom", prompt:"Select...", class: "form-control" %>
                            </div>
                        </div>

                        <div class="col-md-4">
                            <label>Bathrooms</label><br>
                            <div class="list-form-control">
                                <%= f.select :bathroom_gteq, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]], id:"bathroom", prompt:"Select...", class: "form-control" %>
                            </div>
                        </div>
                    </div>
                    <hr>

                    <div class="row">
                        <div class="col-md-4 mb-2">
                            <%= check_box_tag "q[is_tv_eq]", true %> TV
                        </div>
                        <div class="col-md-4 mb-2">
                            <%= check_box_tag "q[is_kitchen_eq]", true %> Kitchen
                        </div>
                        <div class="col-md-4 mb-2">
                            <%= check_box_tag "q[is_internet_eq]", true %> Internet
                        </div>
                        <div class="col-md-4">
                            <%= check_box_tag "q[is_heating_eq]", true %> Heating
                        </div>
                        <div class="col-md-4">
                            <%= check_box_tag "q[is_air_eq]", true %> Air Conditioning
                        </div>
                    </div>
                    <hr>

                    <div class="text-center">
                        <%= f.submit "Search", class: "btn btn-primary" %>
                    </div>
                <% end %>
            </div>
            <br>

            <div class="row">
                <% @arrRooms.each do |room| %>
                    <div class="col-md-4">
                        <div class="card mb-2 search-list">
                            <div class="card-header preview">
                                <%= image_tag room.photos.first.image.url(:medium) %>
                            </div>
                            <div class="card-body room-body">
                                <%= link_to room.listing_name, room %><br>
                                $<%= room.price %> - <%= room.home_type %>
                            </div>
                        </div>
                    </div>
                <% end %>
            </div>
            <div class="text-center">
                    <%= link_to 'Back', root_path, class:"btn btn-primary mt-2" %>
                </div>
        </div>
    </div>

    <div id="right">
        <div id="map" style="width: 100%; height: 100%;">
          <script src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.credentials.google_maps_api_key%>"></script>

          <script>
            function initialize(){

              // Default location if there is no location
              // If there is no result
              var location = {lat: 44.5403, lng: -78.5463};

              <% if @arrRooms.length > 0 %>
                // Get the first latitude and longtitude of the room
                // of the first room on the @arrRooms
                location = {lat: <%= @arrRooms[0].latitude %>, lng: <%= @arrRooms[0].longitude %> }
              <% end %>

              // Get the map
              var map = new google.maps.Map(document.getElementById('map'), {
                center: location,
                zoom: 12
              });

              // Initialize variables
              var marker, infowindow;

              // Looping all rooms and pin the marker
              <% @arrRooms.each do |room| %>
              // Create the marker
              marker = new google.maps.Marker({
                position: {lat: <%= room.latitude %>, lng: <%= room.longitude %> },
                map: map
              });

              // Initialize infowindow
              infowindow = new google.maps.InfoWindow({
                content: "<div> $" + <%= room.price %> + "</div>"
              });
              // Open infowindow
              infowindow.open(map,marker);
              <% end %>
            }

            // Load the map
            google.maps.event.addDomListener(window, 'load', initialize);
          </script>
        </div>
    </div>

<script>
  $('#filter').click(function(){
    if(open) {
      $('#filter').html("More filters <i class='fa fa-chevron-up'></i>")
    } else {
      $('#filter').html("More filters <i class='fa fa-chevron-down'></i>")
    }
    open = !open;
  });
</script>

<script>
  $(function(){
    $("#q_price_gteq").val('100');
    $("#q_price_lteq").val('500');
    $("#slider-range").slider({
      range: true,
      min: 0,
      max: 1000,
      values: [100, 500],
      slide: function(event, ui) {
        $("#q_price_gteq").val(ui.values[0]);
        $("#q_price_lteq").val(ui.values[1]);
      }
    });
  });
</script>

<script>
  $('#start_date').datepicker({
      dateFormat: 'dd-mm-yy',
      minDate: 0,
      maxDate: '3m',
      onSelect: function(selected) {
      $('#end_date').datepicker("option", "minDate", selected);
    }
    });

    $('#end_date').datepicker({
      dateFormat: 'dd-mm-yy',
      minDate: 0,
      maxDate: '3m',
      onSelect: function(selected) {
      $('#start_date').datepicker("option", "maxDate", selected);
    }
  });
</script>

app/views/reviews/_guest_form.html.erb
<!-- Trigger the modal with a button -->
<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal_<%= reservation.id %>">Review Host</button>

<!-- Modal -->
<div id="myModal_<%= reservation.id %>" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <div class="modal-header-text">
                    Please review your host
                </div>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <%= form_for current_user.guest_reviews.new do |f| %>
                    <div class="form-group text-center">
                        <%# <%= f.text_field :star, class: "form-control"%>
                        <div id="stars_<%= reservation.id %>"></div>
                    </div>
                    <div class="form-group text-center">
                        <%= f.text_area :comment, row:3, class: "form-control", placeholder: "Please write some comments" %>
                    </div>

                    <%= f.hidden_field :room_id, value: reservation.room.id %>
                    <%= f.hidden_field :reservation_id, value: reservation.id %>
                    <%= f.hidden_field :host_id, value: reservation.room.user.id %>

                    <div class="text-center">
                        <%= f.submit "Add Review", class: "btn btn-primary btn-block room-form-btn" %>
                    </div>

                <% end %>
            </div>
        </div>
    </div>
</div>

<script>
  $('#stars_<%= reservation.id %>').raty({
    path: '/assets',
    scoreName: 'guest_review[star]',
    score: 1
  });
</script>

app/views/reviews/_guest_list.html.erb
<% if @guest_reviews.count == 0 %>
    <div class="text-center">
        There are no reviews.
    </div>
<% else %>
    <% @guest_reviews.order(id: :desc).each do |review| %>
        <hr>
        <div class="row">
            <div class="col-3 text-center">
                <%= image_tag avatar_url(review.guest), class: "rounded-circle avatar-medium" %> <br><br>
                <strong><%= review.guest.fullname %></strong>
            </div>

            <div class="col-9 mt-2">
                <div id="star_<%= review.id %>">Star: </div>
                <% if current_user && current_user == review.guest %>
                    <span class="float-right">
                        <%= link_to review, method: :delete, data: {confirm: "Are you sure?"} do %>
                            <i class="fa fa-trash-o fa-lg"></i>
                        <% end %>
                    </span>
                <% end %>
                <div>Date: <%= review.created_at.strftime("%v") %></div>
                <div>Comment: <%= review.comment %></div>
            </div>
        </div>

        <script>
          $('#star_<%= review.id %>').raty({
            path: '/assets',
            readOnly: true,
            score: <%= review.star %>
          });
        </script>
    <% end %>
<% end %>

app/views/reviews/_host_form.html.erb
<!-- Trigger the modal with a button -->
<button type="button" class="btn btn-primary active btn-lg" data-toggle="modal" data-target="#myModal_<%= reservation.id %>">Review Guest</button>

<!-- Modal -->
<div id="myModal_<%= reservation.id %>" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <div class="modal-header-text">
                    Please review your guest
                </div>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <%= form_for current_user.host_reviews.new do |f| %>
                    <div class="form-group text-center">
                        <%# <%= f.text_field :star, class: "form-control"%>
                        <div id="stars_<%= reservation.id %>"></div>
                    </div>
                    <div class="form-group text-center">
                        <%= f.text_area :comment, row:3, class: "form-control", placeholder: "Please write some comments" %>
                    </div>
                    <%= f.hidden_field :room_id, value: reservation.room.id %>
                    <%= f.hidden_field :reservation_id, value: reservation.id %>
                    <%= f.hidden_field :guest_id, value: reservation.user.id %>

                    <div class="text-center">
                        <%= f.submit "Add Review", class: "btn btn-primary btn-block room-form-btn" %>
                    </div>

                <% end %>
            </div>
        </div>
    </div>
</div>

<script>
    $('#stars_<%= reservation.id %>').raty({
      path: '/assets',
      scoreName: 'host_review[star]',
      score: 1
    });
</script>

app/views/reviews/_host_list.html.erb
<% if @host_reviews.count == 0 %>
    <div class="text-center">
        There are no reviews.
    </div>
<% else %>
    <% @host_reviews.order(id: :desc).each do |review| %>
        <hr>
        <div class="row">
            <div class="col-3">
                <div class="text-center">
                    <%= image_tag avatar_url(review.host), class: "rounded-circle avatar-medium" %> <br><br>
                    <strong><%= review.host.fullname %></strong>
                </div>
            </div>

            <div class="col-9">
                <div id="star_<%= review.id %>">Star: </div>
                <% if current_user && current_user == review.host %>
                    <span class="float-right">
                        <%= link_to review, method: :delete, data: {confirm: "Are you sure?"} do %>
                            <i class="fa fa-trash-o fa-lg"></i>
                        <% end %>
                    </span>
                <% end %>
                <div>Date: <%= review.created_at.strftime("%v") %></div>
                <div>Comment: <%= review.comment %></div>
            </div>
        </div>

        <script>
          $('#star_<%= review.id %>').raty({
              path: '/assets',
              readOnly: true,
              score: <%= review.star %>
          });
        </script>
    <% end %>
<% end %>